// artsdata-react/src/components/liste/ListeSearch.js
import React, { Component } from 'react'
import './ListeSearch.css'

class ListeSearch extends Component {
  render () {
    return (
      <div className="liste-search">
        <input onChange={this.props.changeHandler} type="text" placeholder="søk etter art..." />
      </div>
    )
  }
}

export default ListeSearch

// artsdata-angular2/app/components/liste/liste-search.component.ts
import { Component } from "@angular/core";


@Component ({
  moduleId: module.id,
  selector: 'liste-search',
  templateUrl: 'liste-search.component.html'
})

export class ListeSearchContainer {
  
}

<link rel="stylesheet" href="liste-search.css">

<div class="liste-search">
  <input #field type="text" (input)="searchField.emit(field.value)" placeholder="søk etter art..."/>
</div>
