// artsdata-react/src/components/liste/ListeElement.js
import React, { Component } from 'react'
import './ListeElements.css'

class ListeElement extends Component {
  render() {
    return (
      <div className="listeElement">
        <input type="checkbox" className="toggle-checkbutton" id={this.props.id} />
        <label htmlFor={ this.props.id }>
          <strong>{this.props.data.Name}</strong>
        </label>
        <div className="notes">
          <dl>
            <dt>Vitenskapelig navn</dt>
            <dd>{this.props.data.ScientificName}</dd>
            <br/>
            <dt>Dato</dt>
            <dd>{this.props.data.CollectedDate}</dd>
            <dt>Sted</dt>
            <dd>{this.props.data.Municipality}, {this.props.data.County} (<a target="_blank" href={'https://www.google.com/maps/preview/@' + this.props.data.Latitude + ',' + this.props.data.Longitude + ',14z'}>{this.props.data.Latitude}, {this.props.data.Longitude}</a>)</dd>
            <dt>Registrert av</dt>
            <dd>{this.props.data.Collector}&nbsp;</dd>
            <dt>Beskrivelse</dt>
            <dd>{this.props.data.Notes}&nbsp;</dd>
          </dl>
        </div>
      </div>
    );
  }
}

export default ListeElement

// artsdata-angular2/app/components/liste/liste-element.component.ts
import { Component, Input } from "@angular/core";

@Component({
  moduleId: module.id,
  selector: 'liste-element',
  templateUrl: 'liste-element.component.html'
})
export class ListeElementComponent {
  @Input() name:string;
}

<input type="checkbox" class="toggle-checkbutton" id="1" />
<label for="1">no</label>

<div class="notes">
  <dl>
    <dt>Vitenskapelig navn</dt>
    <dd>&nbsp;</dd>
    <br/>
    <dt>Dato</dt>
    <dd>&nbsp;</dd>
    <dt>Sted</dt>
    <dd>&nbsp;)</dd>
    <dt>Registrert av</dt>
    <dd>&nbsp;</dd>
    <dt>Beskrivelse</dt>
    <dd>&nbsp;</dd>
  </dl>
</div>
